Repository ThugMS/GameLab_Week1, pull requests merged in 2023-08, with the labels that each got.

#1 [Feat] : Branch 설명
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/Player.cs.meta
Labels: Feat, minseok

#3 [Feat] : 애니메이션 추가
  Assets/Animation.meta
  Assets/Animation/Circle.controller
  Assets/Animation/Circle.controller.meta
  Assets/Animation/attack.anim
  Assets/Animation/attack.anim.meta
  Assets/Animation/counter.anim
  Assets/Animation/counter.anim.meta
  Assets/Animation/hit.anim
  Assets/Animation/hit.anim.meta
  Assets/Animation/idle.anim
  Assets/Animation/idle.anim.meta
  Assets/Animation/smash.anim
  Assets/Animation/smash.anim.meta
  Assets/Scenes/woo test.unity
  Assets/Scenes/woo test.unity.meta
  ProjectSettings/SceneTemplateSettings.json
Labels: Feat, jeongwoo

#4 [Feat] : Player 생성, 움직임 구현
  .vsconfig
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Player.prefab.meta
  Assets/Scenes/SampleScene.unity
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/PlayerManager.cs.meta
  ProjectSettings/TagManager.asset
  ProjectSettings/TimelineSettings.asset
Labels: Feat, minseok

#7 [Feat] : Stage 1 추가
  Assets/Prefabs/ShortenPlatform.prefab
  Assets/Resources/Prefabs/DefaultPlatform.prefab
  Assets/Resources/Prefabs/DefaultPlatform.prefab.meta
  Assets/Resources/Prefabs/DropPlatform.prefab
  Assets/Resources/Prefabs/RotatePlatform .prefab
  Assets/Resources/Prefabs/RotatePlatform.prefab
  Assets/Resources/Prefabs/RotatePlatform.prefab.meta
  Assets/Resources/Prefabs/ShortenPlatform.prefab
  Assets/Resources/Prefabs/Stage1.prefab
  Assets/Resources/Prefabs/Stage1.prefab.meta
  Assets/Scenes/Platform Test.unity
  Assets/Scenes/Stage1.unity
  Assets/Scenes/Stage1.unity.meta
  Assets/Scripts/Test/Platform.cs
  Assets/Scripts/Test/Stage1.cs
  Assets/Scripts/Test/Stage1.cs.meta
Labels: Feat, gyeongse

#8 [Feat] : player 공격 피격 구현
  Assets/Animation/Knight.controller
  Assets/Animation/attack.anim
  Assets/Prefabs/Player.prefab
  Assets/Scenes/MS.unity
  Assets/Scenes/MS.unity.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/PlayerSword.cs
  Assets/Scripts/Test/PlayerSword.cs.meta
  ProjectSettings/TagManager.asset
Labels: Feat, minseok

#10 [Feat] : 카메라 이동 제한 추가, 인디케이터 스크립트 삭제
  Assets/Animation/sizeUpDuringFadeOut.anim
  Assets/Prefabs/Player.prefab
  Assets/Scenes/woo test.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/FieldData.cs
  Assets/Scripts/Test/FieldData.cs.meta
Labels: Feat, jeongwoo

#11 [Fix] : 공격하면서 선입력 수정
  Assets/Animation/Knight.controller
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerSword.cs
Labels: Fix, minseok

#13 [Test] : 자동화 Reviewer폴더 삭제
  .github/workflows/main.yml
  Assets/Scripts/Test/Player.cs
Labels: minseok

#15 [Feat] : 공격 넉백 모두 추가
  Assets/Animation/Knight.controller
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Test/Player.cs
Labels: Feat, minseok

#16 [Feat] : Indicator 추가
  Assets/Prefabs/Player.prefab
  Assets/Resources/Prefabs/DefaultPlatform.prefab
  Assets/Resources/Prefabs/DropPlatform.prefab
  Assets/Resources/Prefabs/RotatePlatform.prefab
  Assets/Resources/Prefabs/ShortenPlatform.prefab
  Assets/Scenes/Platform Test.unity
  Assets/Scenes/Stage1.unity
  Assets/Scenes/woo test.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/FieldData.cs
  Assets/Scripts/Test/Indicator.cs
  Assets/Scripts/Test/IndicatorManager.cs
  Assets/Scripts/Test/Platform.cs
  Assets/Scripts/Test/Stage1.cs
Labels: Feat, gyeongse

#18 [Fix] : Main 씬 수정
  Assets/Resources/Prefabs/DropPlatform.prefab
  Assets/Resources/Prefabs/RotatePlatform.prefab
  Assets/Resources/Prefabs/ShortenPlatform.prefab
  Assets/Scenes/Main.unity
  Assets/Scenes/Stage1.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/Indicator.cs
Labels: Fix, gyeongse

#19 [Fix] : Main 씬 합치기 수정
  Assets/Resources/Prefabs/Stage1.prefab
  Assets/Scenes/MS.unity
  Assets/Scenes/Main.unity
Labels: Fix

#20 [Fix] : 강공격 범위 오류 수정
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerSword.cs
Labels: Fix, minseok

#21 [Feat] : 튜토리얼 룸 기능 완성
  Assets/Prefabs/Tutorial Button.prefab
  Assets/Prefabs/Tutorial Room.prefab
  Assets/Scenes/woo test.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/TutorialButton.cs
  Assets/Scripts/Test/TutorialRoom.cs
  Assets/Scripts/Test/TutorialRoom.cs.meta
Labels: Feat, jeongwoo

#22 Gyeongse
  Assets/Prefabs/Indicator.prefab
  Assets/Prefabs/Indicator.prefab.meta
  Assets/Prefabs/Player Indicator 2.prefab
  Assets/Prefabs/Player Indicator 2.prefab.meta
  Assets/Resources/Prefabs/DeadLine.prefab
  Assets/Resources/Prefabs/DeadLine.prefab.meta
  Assets/Resources/Prefabs/DefaultPlatform.prefab
  Assets/Resources/Prefabs/DropPlatform.prefab
  Assets/Resources/Prefabs/RotatePlatform.prefab
  Assets/Resources/Prefabs/ShortenPlatform.prefab
  Assets/Scenes/Stage1.unity
  Assets/Scripts/Test/Indicator.cs
  Assets/Scripts/Test/Revival.cs
  Assets/Scripts/Test/Revival.cs.meta
  Assets/Scripts/Test/RevivalManage.cs
  Assets/Scripts/Test/RevivalManage.cs.meta
  ProjectSettings/TagManager.asset
Labels: Feat, gyeongse

#23 [Feat] : 카운터 이펙트 추가
  Assets/Animation/CounterEffect.controller
  Assets/Prefabs/Player.prefab
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerSword.cs
Labels: Feat, minseok

#25 Jeongwoo
  Assets/Animation/SmashFadeOut.anim
  Assets/Animation/attack.anim
  Assets/Animation/counter.anim
  Assets/Animation/hit.anim
  Assets/Animation/idle.anim
  Assets/Animation/smash.anim
  Assets/Prefabs/Castle Far.prefab
  Assets/Prefabs/Effect Manager.prefab
  Assets/Prefabs/Effect Manager.prefab.meta
  Assets/Prefabs/Field.prefab
  Assets/Prefabs/Main.prefab
  Assets/Prefabs/Player 1.prefab
  Assets/Prefabs/Player 1.prefab.meta
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/smash effect.prefab
  Assets/Scripts/Test/AnimationEffect.cs
  Assets/Scripts/Test/AnimationEffect.cs.meta
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/EffectBundle.cs
  Assets/Scripts/Test/EffectBundle.cs.meta
  Assets/Scripts/Test/EffectManager.cs
  Assets/Scripts/Test/EffectManager.cs.meta
  Assets/Scripts/Test/TutorialRoom.cs
Labels: bug, Feat, Fix, jeongwoo

#26 Jeongwoo
  Assets/Animation/counter.anim
  Assets/Animation/hit.anim
  Assets/Animation/smash.anim
Labels: Fix, jeongwoo

#27 [Fix] : 플레이어 수정
  Assets/Animation/counter.anim
  Assets/Animation/hit.anim
  Assets/Animation/idle.anim
  Assets/Animation/smash.anim
  Assets/Prefabs/Player.prefab
Labels: Fix, jeongwoo

#28 [Feat] : 공격성공 시, 카메라 흔들림 연결
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/Player.cs
Labels: Feat, minseok

#29 [Fix] : 카메라 쉐이커 수정
  Assets/Scenes/woo test.unity
  Assets/Scripts/Test/CameraShaker.cs
Labels: Fix, jeongwoo

#30 [Fix] : 튜토리얼룸 부등호 추가
  Assets/Animation/SmashFadeOut.anim
  Assets/Prefabs/Tutorial Room.prefab
Labels: Fix, jeongwoo

#31 [Feat] : 인디케이터 기능 구현
  Assets/Resources/Prefabs/Indicator.prefab
  Assets/Resources/Prefabs/Indicator.prefab.meta
  Assets/Scenes/Main.unity
  Assets/Scenes/Stage1.unity
  Assets/Scripts/Test/Indicator.cs
Labels: Feat, Fix, gyeongse

#32 [Feat] : 튜토리얼 키 체크 표시 진행중
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Tutorial Room.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/CameraShaker.cs
  Assets/Scripts/Test/EffectManager.cs
  Assets/Scripts/Test/EventManager.cs
  Assets/Scripts/Test/EventManager.cs.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/PlayerTutorial.cs
  Assets/Scripts/Test/PlayerTutorial.cs.meta
Labels: Feat, minseok

#33 [Feat] : 무적 시간 수정 및 키패드 체크 추가
  Assets/Scenes/woo test.unity
Labels: Feat, Fix, minseok

#34 [Fix] : Indicator 수정
  Assets/Resources/Prefabs/DropPlatform.prefab
  Assets/Scenes/Stage1.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/Indicator.cs
  Assets/Scripts/Test/Platform.cs
Labels: Fix, gyeongse

#35 [Feat] : 인디케이터 방향표시 추가
  Assets/Prefabs/Indicator.prefab
  Assets/Prefabs/Player Indicator.prefab
  Assets/Resources/Prefabs/Indicator.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/Indicator.cs
Labels: Feat, jeongwoo

#36 save
  Assets/Prefabs/PlayerManager 1.prefab
  Assets/Prefabs/PlayerManager 1.prefab.meta
  Assets/Prefabs/PlayerManager.prefab
  Assets/Prefabs/PlayerManager.prefab.meta
  Assets/Prefabs/Start Set.prefab
  Assets/Prefabs/Start Set.prefab.meta
  Assets/Prefabs/Tutorial Room.prefab
  Assets/Prefabs/counter effect.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/Indicator.cs
Labels: jeongwoo

#37 [Feat] : Main 씬에 모든 기능 병합
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/Start Set.prefab
  Assets/Prefabs/Tutorial Room.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/PlayerTutorial.cs
  Assets/Scripts/Test/Stage1.cs
  Assets/Scripts/Test/TutorialButton.cs
  Assets/Scripts/Test/TutorialRoom.cs
Labels: Feat, minseok

#38 [Feat] : 이펙트 수정 및 플레이어 깃털 추가
  Assets/Animation/attack.anim
  Assets/Animation/counter.anim
  Assets/Animation/hit.anim
  Assets/Animation/idle.anim
  Assets/Animation/sizeUpDuringFadeOut.anim
  Assets/Animation/smash.anim
  Assets/Prefabs/Player.prefab
  Assets/Prefabs/PlayerManager 1.prefab
  Assets/Prefabs/PlayerManager 1.prefab.meta
  Assets/Prefabs/PlayerManager.prefab
  Assets/Prefabs/PlayerManager.prefab.meta
  Assets/Prefabs/Start Set.prefab
  Assets/Prefabs/Tutorial Room.prefab
  Assets/Scenes/Main.unity
Labels: Feat, jeongwoo

#39 [Feat] : stage2 추가
  Assets/Resources/Prefabs/Stage1.prefab
  Assets/Resources/Prefabs/Stage2.prefab
  Assets/Resources/Prefabs/Stage2.prefab.meta
  Assets/Scenes/Stage1.unity
  Assets/Scenes/gs test.unity
  Assets/Scenes/gs test.unity.meta
  Assets/Scripts/Test/Base Stage.cs
  Assets/Scripts/Test/Base Stage.cs.meta
  Assets/Scripts/Test/Platform.cs
  Assets/Scripts/Test/Stage1.cs
  Assets/Scripts/Test/Stage2.cs
  Assets/Scripts/Test/Stage2.cs.meta
  Assets/Scripts/Test/TutorialRoom.cs
Labels: Feat, gyeongse

#40 [Fix] : Player2 기사 깃털 색깔 변경
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/Player.cs
Labels: Feat, minseok

#41 [Feat] : 하트 UI 작업
  Assets/Animation/heart.controller
  Assets/Animation/heart.controller.meta
  Assets/Animation/heartbeat.anim
  Assets/Animation/heartbeat.anim.meta
  Assets/Prefabs/heart .prefab
  Assets/Prefabs/heart .prefab.meta
  Assets/Scenes/woo test.unity
Labels: Feat, jeongwoo

#42 [Feat] : ESC UI 생성
  Assets/Animation/Knight.controller
  Assets/Prefabs/ESCMenu.prefab
  Assets/Prefabs/ESCMenu.prefab.meta
  Assets/Prefabs/ESCPanel.prefab
  Assets/Prefabs/ESCPanel.prefab.meta
  Assets/Scenes/Minseok.unity
  Assets/Scenes/Minseok.unity.meta
  Assets/Scripts/Test/ESCMenu.cs
  Assets/Scripts/Test/ESCMenu.cs.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/PlayerSword.cs
Labels: Feat, minseok

#44 [Feat] : ESC Menu 완성
  Assets/Scenes/Minseok.unity
  Assets/Scripts/Test/ESCMenu.cs
Labels: Feat, Fix, minseok

#46 원인찾음 ㅋㅋ
  Assets/Prefabs/Heart UI.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/DeadLine.cs
  Assets/Scripts/Test/DeadLine.cs.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/Revival.cs
  Assets/Scripts/Test/UIHeartContainer.cs
Labels: bug, jeongwoo

#47 [Feat] : 게임매니저 추가, 사망 및 부활 처리 수정
  Assets/Prefabs/Main.prefab
  Assets/Prefabs/Player.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/DeadLine.cs
  Assets/Scripts/Test/GameManager.cs
  Assets/Scripts/Test/GameManager.cs.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/Revival.cs
  Assets/Scripts/Test/SnowController.cs
  Assets/Scripts/Test/SnowController.cs.meta
  Assets/Scripts/Test/TutorialRoom.cs
Labels: Feat, Fix, jeongwoo

#48 [Feat] : 스매시 이펙트 추가
  Assets/Prefabs/smash particle.prefab
  Assets/Prefabs/smash particle.prefab.meta
Labels: Feat, jeongwoo

#49 [Feat] : 카메라 컨트롤러 바운더리 교체 함수 추가
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/Parallax.cs
  Assets/Scripts/Test/TutorialRoom.cs
Labels: Feat, jeongwoo

#53 [Fix] : 충돌 수정
  Assets/Resources/Prefabs/Stage3.prefab
  Assets/Scenes/Main.unity
  Assets/Scenes/gs test.unity
  Assets/Scripts/Test/StageMenu.cs
Labels: Fix, gyeongse

#54 [Fix] : 하트 애니메이터가 꺼져있을 때 초기화하는 오류 수정
  Assets/Scripts/Test/UIController.cs
  Assets/Scripts/Test/UIHeartContainer.cs
Labels: Fix, jeongwoo

#55 [Fix] : 인디케이터 첫 화면에서 보이지 않게 수정
  Assets/Scripts/Test/IndicatorManager.cs
  Assets/Scripts/Test/UIController.cs
Labels: Fix, jeongwoo

#56 [Feat] : Main화면 병합 완료
  Assets/Animation/SmashEffect.controller
  Assets/Prefabs/ESCCanvas.prefab
  Assets/Prefabs/ESCCanvas.prefab.meta
  Assets/Prefabs/MainImage.prefab
  Assets/Prefabs/MainImage.prefab.meta
  Assets/Prefabs/PlayerManager.prefab
  Assets/Prefabs/hit particle.prefab
  Assets/Scenes/Main.unity
  Assets/Scenes/Minseok.unity
  Assets/Scripts/Test/ESCMenu.cs
  Assets/Scripts/Test/GameManager.cs
  Assets/Scripts/Test/MainScreen.cs
  Assets/Scripts/Test/MainScreen.cs.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/StageMenu.cs
Labels: Feat, Fix, minseok

#58 [Fix] : GameManager 수정
  Assets/Scenes/Main.unity
Labels: Fix, minseok

#59 [Fix] : 튜토리얼룸 버튼 체크 안 되는 오류 수정
  Assets/Animation/Check.controller
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/TutorialButton.cs
  Assets/Scripts/Test/TutorialRoom.cs
Labels: Fix, jeongwoo

#60 [Fix] : Stage 초기화 작성
  Assets/Resources/Prefabs/Stage3.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/Base Stage.cs
  Assets/Scripts/Test/Stage1.cs
  Assets/Scripts/Test/Stage2.cs
  Assets/Scripts/Test/Stage3.cs
  Assets/Scripts/Test/StageMenu.cs
  Assets/Scripts/Test/TutorialRoom.cs
Labels: Feat, Fix, gyeongse

#62 [Fix] : 메인 화면 복귀 기능
  Assets/Prefabs/MainImage.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/GameManager.cs
  Assets/Scripts/Test/MainScreen.cs
  Assets/Scripts/Test/StageMenu.cs
  Assets/Scripts/Test/UIHeartContainer.cs
Labels: Fix, minseok

#63 [Fix] : 초반 움직임 동기화 수정
  Assets/Scripts/Test/ESCMenu.cs
  Assets/Scripts/Test/Player.cs
Labels: Fix, minseok

#64 Jeongwoo
  Assets/Animation/MainMessage.controller
  Assets/Animation/MainMessage.controller.meta
  Assets/Animation/blinkingMessage.anim
  Assets/Animation/blinkingMessage.anim.meta
  Assets/Prefabs/MainImage.prefab
  Assets/Resources/Prefabs/Stage1.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/CameraController.cs
  Assets/Scripts/Test/GameManager.cs
  Assets/Scripts/Test/IndicatorManager.cs
  Assets/Scripts/Test/IndicatorManager.cs.meta
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/Revival.cs
  Assets/Scripts/Test/TutorialRoom.cs
  Assets/Scripts/Test/UIHeartContainer.cs
Labels: Fix, jeongwoo

#65 [Fix] : 의도하지 않은 플랫폼 생성 버그 수정
  Assets/Resources/Prefabs/Stage1.prefab
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/Stage1.cs
Labels: Fix, jeongwoo

#66 [Fix] : 튜토리얼룸 베이스 스테이지 널 레퍼런스 수정
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/GameManager.cs
  Assets/Scripts/Test/Stage1.cs
Labels: Fix, jeongwoo

#67 [Feat] : 튜토리얼룸 배경 색상 조정
  Assets/Scenes/Main.unity
Labels: Fix, jeongwoo

#68 [Fix] : UI 작동 오류 수정
  Assets/Scripts/Test/ESCMenu.cs
  Assets/Scripts/Test/StageMenu.cs
  Assets/Scripts/Test/UIHeartContainer.cs
Labels: Fix, minseok

#69 [Fix] : 맵이 초기화되던 오류 수정
  Assets/Scripts/Test/ESCMenu.cs
  Assets/Scripts/Test/TutorialRoom.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
  ProjectSettings/BurstAotSettings_StandaloneWindows.json
  ProjectSettings/CommonBurstAotSettings.json
Labels: Fix, minseok, jeongwoo

#70 [Feat] : 승자 화면 추가
  Assets/Prefabs/VitoryImage.prefab
  Assets/Prefabs/VitoryImage.prefab.meta
  Assets/Scenes/Main.unity
  Assets/Scripts/Test/GameManager.cs
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/StageMenu.cs
  Assets/Scripts/Test/VitoryScreen.cs
  Assets/Scripts/Test/VitoryScreen.cs.meta
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: Feat, minseok

#71 [Fix] : 플레이어 Drag 변수 수정 및 튜토리얼 초기화 오류 수정
  Assets/Scripts/Test/Player.cs
  Assets/Scripts/Test/PlayerManager.cs
  Assets/Scripts/Test/StageMenu.cs
  Assets/Scripts/Test/TutorialRoom.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: Fix, minseok

#72 [Fix] : 무한 점프 오류 Collider 수정
  Assets/Resources/Prefabs/ShortenPlatform.prefab
  Assets/Resources/Prefabs/Stage3.prefab
  Assets/Scripts/Test/Player.cs
  Assets/TextMesh Pro/Resources/Fonts & Materials/LiberationSans SDF - Fallback.asset
Labels: Fix, minseok, gyeongse
